<?php

namespace app\common\validate;

class Goods extends Base
{
    // 验证规则
    protected $rule = [
        'id' => 'require|number|max:11',
        'type_id' => 'require|number|egt:0',
        'tuijian' => 'number|egt:0',
        'click' => 'number|egt:0',
        'title' => 'require|max:150',
        'seotitle' => 'max:150',
        'keywords' => 'max:60',
        'description' => 'max:250',
        'sell_point' => 'max:150',
        'litpic' => 'require|max:150',
        'goods_img' => 'require|max:150',
        'sn' => 'require|max:60',
        'price' => 'require|regex:/^\d{0,10}(\.\d{0,2})?$/|elt:market_price',
        'market_price' => 'require|regex:/^\d{0,10}(\.\d{0,2})?$/',
        'cost_price' => 'regex:/^\d{0,10}(\.\d{0,2})?$/',
        'shipping_fee' => 'regex:/^\d{0,10}(\.\d{0,2})?$/',
        'goods_number' => 'number|between:0,99999',
        'sale' => 'number|egt:0',
        'warn_number' => 'number|between:1,99',
        'goods_weight' => 'regex:/^\d{0,10}(\.\d{0,2})?$/',
        'point' => 'number|between:1,99999',
        'comment_number' => 'number|egt:0',
        'promote_price' => 'regex:/^\d{0,10}(\.\d{0,2})?$/|elt:price',
        'promote_start_date' => 'number|egt:0',
        'promote_end_date' => 'number|egt:0|gt:promote_start_date',
        'brand_id' => 'number|egt:0',
        'user_id' => 'number|egt:0',
        'listorder' => 'number|egt:0',
        'status' => 'in:0,1,2,3',
        'shop_id' => 'number|egt:0',
        'update_time' => 'require|number|gt:0',
        'add_time' => 'require|number|gt:0',
    ];
	
	protected $message = [
        'id.require' => 'ID不能为空',
        'id.number' => 'ID必须是数字',
        'id.gt' => 'ID格式不正确',
        'type_id.require' => '栏目ID不能为空',
        'type_id.number' => '栏目ID必须是数字',
        'type_id.egt' => '栏目ID格式不正确',
        'tuijian.number' => '推荐等级必须是数字',
        'tuijian.egt' => '推荐等级格式不正确',
        'click.number' => '点击量必须是数字',
        'click.egt' => '点击量格式不正确',
        'title.require' => '标题不能为空',
        'title.max' => '标题不能超过150个字符',
        'seotitle.max' => 'SEO标题不能超过150个字符',
        'keywords.max' => '关键词不能超过60个字符',
        'description.max' => '描述不能超过250个字符',
        'sell_point.max' => '卖点描述不能超过150个字符',
        'litpic.max' => '缩略图不能超过150个字符',
        'goods_img.require' => '商品图片不能为空',
        'goods_img.max' => '商品的实际大小图片不能超过150个字符',
        'sn.require' => '货号不能为空',
        'sn.max' => '货号不能超过60个字符',
        'price.require' => '产品价格不能为空',
        'price.regex' => '产品价格只能带2位小数的数字',
        'price.elt' => '原价必须大于产品价格',
        'market_price.require' => '原价不能为空',
        'market_price.regex' => '原价格式不正确，原价只能带2位小数的数字',
        'cost_price.regex' => '成本价格格式不正确，成本价格只能带2位小数的数字',
        'shipping_fee.regex' => '运费格式不正确，运费只能带2位小数的数字',
        'goods_number.number' => '库存必须是数字',
        'goods_number.between' => '库存只能0-99999',
        'sale.number' => '销量必须是数字',
        'sale.egt' => '销量格式不正确',
        'warn_number.number' => '商品报警数量必须是数字',
        'warn_number.between' => '商品报警数量只能1-99',
        'goods_weight.regex' => '重量格式不正确，重量只能带2位小数的数字',
        'point.number' => '购买该商品时每笔成功交易赠送的积分数量必须是数字',
        'point.between' => '购买该商品时每笔成功交易赠送的积分数量只能1-99999',
        'comment_number.number' => '评论次数必须是数字',
        'comment_number.egt' => '评论次数格式不正确',
        'promote_price.regex' => '促销价格格式不正确，促销价格只能带2位小数的数字',
        'promote_price.elt' => '促销价格必须小于产品价格',
        'promote_start_date.number' => '促销价格开始日期必须是数字',
        'promote_start_date.egt' => '促销价格开始日期格式不正确',
        'promote_end_date.number' => '促销价格结束日期必须是数字',
        'promote_end_date.egt' => '促销价格结束日期格式不正确',
        'promote_end_date.gt' => '促销价格开始日期必须小于结束时间',
        'brand_id.number' => '商品品牌ID必须是数字',
        'brand_id.egt' => '商品品牌ID格式不正确',
        'user_id.number' => '发布者ID必须是数字',
        'user_id.egt' => '发布者ID格式不正确',
        'listorder.number' => '排序必须是数字',
        'listorder.egt' => '排序格式不正确',
        'status.in' => '商品状态 0正常 1已删除 2下架 3申请上架',
        'shop_id.number' => '店铺ID必须是数字',
        'shop_id.egt' => '店铺ID格式不正确',
        'add_time.require' => '添加时间不能为空',
        'add_time.number' => '添加时间格式不正确',
        'add_time.gt' => '添加时间格式不正确',
        'update_time.require' => '更新时间不能为空',
        'update_time.number' => '更新时间格式不正确',
        'update_time.gt' => '更新时间格式不正确',
    ];

    protected $scene = [
        'add' => ['type_id', 'tuijian', 'click', 'title', 'seotitle', 'keywords', 'description', 'sell_point', 'litpic', 'goods_img', 'sn', 'price', 'market_price', 'cost_price', 'shipping_fee', 'goods_number', 'sale', 'warn_number', 'goods_weight', 'point', 'comment_number', 'promote_price', 'promote_start_date', 'promote_end_date', 'brand_id', 'user_id', 'listorder', 'status', 'update_time', 'add_time'],
        'edit' => ['type_id', 'tuijian', 'click', 'title', 'seotitle', 'keywords', 'description', 'sell_point', 'litpic', 'goods_img', 'sn', 'price', 'market_price', 'cost_price', 'shipping_fee', 'goods_number', 'sale', 'warn_number', 'goods_weight', 'point', 'comment_number', 'promote_price', 'promote_start_date', 'promote_end_date', 'brand_id', 'user_id', 'listorder', 'status', 'update_time'],
        'del' => ['id'],
    ];
}